# Copyright (C) 2018 SCARV project <info@scarv.org>
#
# Use of this source code is restricted per the MIT license, a copy of which 
# can be found at https://opensource.org/licenses/MIT (or should be included 
# as LICENSE.txt within the associated archive or repository).

# =============================================================================

RUN apt-get --assume-yes --quiet install libtool libusb-1.0 pkg-config texinfo

RUN wget --quiet https://developer.arm.com/-/media/Files/downloads/gnu-rm/8-2018q4/gcc-arm-none-eabi-8-2018-q4-major-linux.tar.bz2 \
 && tar --extract --directory /opt --file gcc-arm-none-eabi-8-2018-q4-major-linux.tar.bz2 \
 && rm --force gcc-arm-none-eabi-8-2018-q4-major-linux.tar.bz2

RUN git clone --branch v0.10.0 https://git.code.sf.net/p/openocd/code openocd-0.10.0 \
 && cd ./openocd-0.10.0 \
 && wget --no-check-certificate --content-disposition --quiet --output-document=- https://raw.github.com/danpage/scale-hw/master/target/lpc1313fbd48/openocd-0.10.0.patch | patch -p1 \
 && ./bootstrap \
 && ./configure --prefix /opt/openocd-0.10.0 --enable-jlink \
 && make CFLAGS="-Wno-implicit-fallthrough -Wno-format-overflow" all install

RUN echo 'export PATH="/opt/gcc-arm-none-eabi-8-2018-q4-major/bin:/opt/openocd-0.10.0/bin:${PATH}"' >> /etc/profile

# =============================================================================
