# Copyright (C) 2018 SCARV project <info@scarv.org>
#
# Use of this source code is restricted per the MIT license, a copy of which 
# can be found at https://opensource.org/licenses/MIT (or should be included 
# as LICENSE.txt within the associated archive or repository).

# =============================================================================

RUN wget --quiet https://developer.arm.com/-/media/Files/downloads/gnu-rm/8-2018q4/gcc-arm-none-eabi-8-2018-q4-major-linux.tar.bz2 \
 && tar --extract --directory ${DEPS} --file gcc-arm-none-eabi-8-2018-q4-major-linux.tar.bz2 \
 && rm --force gcc-arm-none-eabi-8-2018-q4-major-linux.tar.bz2

ENV PATH "${DEPS}/gcc-arm-none-eabi-8-2018-q4-major/bin:${PATH}"

RUN apt-get --assume-yes --quiet install g++ cmake libboost-all-dev

RUN git clone https://github.com/sca-research/GILES.git ./GILES \
 && cd ./GILES \
 && git checkout a2d541bedd4b52dc87595e5b8f9ccf7df51beaa8 \
 && git submodule update --init --recursive \
 && cmake . && cmake --build . && cmake --install . --prefix ${DEPS}/giles \
 && cd .. \
 && rm --force --recursive ./GILES

ENV PATH "${DEPS}/giles/bin:${PATH}"
ENV LD_LIBRARY_PATH "${DEPS}/giles/lib:${LD_LIBRARY_PATH}"

# =============================================================================
